### ISSUE TITLE
Bot can't follow people?

### ISSUE THREAD

**Issue by sixohsix** [sixohsix/twitter#10]
Error when trying to "follow chrisokc":

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/twitter-1.3.1-py2.6.egg/twitter/ircbot.py", line 157, in handle_privmsg
    self.follow(conn, evt, args[1])
  File "/usr/local/lib/python2.6/dist-packages/twitter-1.3.1-py2.6.egg/twitter/ircbot.py", line 191, in follow
    friends = [x['name'] for x in self.twitter.statuses.friends()]
  File "/usr/local/lib/python2.6/dist-packages/twitter-1.3.1-py2.6.egg/twitter/api.py", line 114, in **call**
    raise TwitterHTTPError(e, uri, self.format, self.encoded_args)
TwitterHTTPError: Twitter sent status 404 for URL: statuses/friends.json using parameters: ()
details: {"request":"/statuses/friends.json","error":"Not found"}

**Comment by hugovk** [comment]
Thanks for the report, however we're no longer maintaining this project and will be archiving it.

The existing releases and code will remain available in their current state.
