### ISSUE TITLE
Get list members: "Sorry, that page does not exist"

### ISSUE THREAD

**Issue by hugovk** [sixohsix/twitter#277]
To reproduce:

```python
>>> from twitter import *
>>> t = Twitter(auth=OAuth(A, B, C, D))
>>> t.statuses.user_timeline(screen_name="billybob")[0]['text']  # sanity check
u'Hey monkey nuts were now live on hulu! Check us out!\nhttp://www.hulu.com/watch/221783/trailer-trash-faceoff?from=fb_share'
```
So far so good. But using the examples examples from https://github.com/sixohsix/twitter/blob/master/README#L107-112, and the [example list does exist](https://twitter.com/tamtar/lists/things-that-are-rad/members):

```python
>>> t._("tamtar")._("things-that-are-rad").members()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/twitter/api.py", line 266, in __call__
    handle = urllib_request.urlopen(req, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twitter/api.py", line 299, in _handle_response
    Get RESTful data by accessing members of this class. The result
twitter.api.TwitterHTTPError: Twitter sent status 404 for URL: 1.1/tamtar/things-that-are-rad/members.json using parameters: (oauth_consumer_key=snip&oauth_nonce=snip&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1423428543&oauth_token=snip&oauth_version=1.0&oauth_signature=snip)
details: {"errors":[{"message":"Sorry, that page does not exist","code":34}]}
>>> 
>>> t.user.list.members(user="tamtar", list="things-that-are-rad")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/twitter/api.py", line 266, in __call__
    handle = urllib_request.urlopen(req, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/twitter/api.py", line 299, in _handle_response
    Get RESTful data by accessing members of this class. The result
twitter.api.TwitterHTTPError: Twitter sent status 404 for URL: 1.1/tamtar/things-that-are-rad/members.json using parameters: (oauth_consumer_key=snip&oauth_nonce=snip&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1423428588&oauth_token=snip&oauth_version=1.0&oauth_signature=snip)
details: {"errors":[{"message":"Sorry, that page does not exist","code":34}]}
```

The problem is that `uriBase` in `__call__` is `https://api.twitter.com/1.1/tamtar/things-that-are-rad/members.json` and not something like `https://api.twitter.com/1.1/lists/members.json`. See the [Twitter docs](https://dev.twitter.com/rest/reference/get/lists/members).

This works:
```python
t.lists.members(owner_screen_name="tamtar", slug="things-that-are-rad")
```

**Comment by RouxRC** [comment]
Hi @Hugovk, I'm not sure I get your problem here. The API route to use is lists.members so it makes sense to get a 404 for other routes such as user.list.members or tamtar.things-that-are-rad/members no?

**Comment by hugovk** [comment]
Correct. The problem is with the README documentation showing outdated examples.

**Comment by RouxRC** [comment]
Ah I get it now, indeed well caught!
